version: '3.8'

services:
  app:
    build: .
    container_name: honojs-rest-app
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_PORT=3000
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always
