apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.httpRoute.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
  rules:
    - matches:
        - path:
            type: Prefix
            value: {{ .Values.httpRoute.path }}
      backendRefs:
        - name: {{ include "go-openapi-rest-app.fullname" . }}
          port: {{ .Values.service.port }}
