apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: nginx
  listeners:
    - name: https
      protocol: HTTPS
      port: {{ .Values.gateway.port }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.certificate.secretName }}
            kind: Secret
            group: ""
