apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs-grpc-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ include "nodejs-grpc-app.name" . }}
