# Override the chart's default name
nameOverride: ""

# Override the full name template
fullnameOverride: ""

# Override the namespace where resources will be deployed
namespaceOverride: ""


replicaCount: 3

image:
  repository: nodejs-honojs-rest-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

gateway:
  name: nodejs-honojs-gateway
  namespace: default
  port: 443

httpRoute:
  name: nodejs-honojs-route
  host: honojs.services.pwc.com
  path: /

issuer:
  name: azure-key-vault-issuer
  namespace: default
  azureKeyVault:
    tenantId: "<PLUG-tenant-id>"
    clientId: "<PLUG-client-id>"
    clientSecret: "<PLUG-client-secret>"
    keyVaultName: "<PLUG-key-vault-name>"

certificate:
  name: nodejs-honojs-cert
  dnsNames:
    - honojs.services.pwc.com
  secretName: nodejs-honojs-secret
